Disable Epicea during package loading
We have recently experienced higher-than-tolerable failure rate on
Github CI caused by some hiccup in Epicea:

    OmFileStoreReadingError: Reading entry from File @ /home/runner/work/MachineArithmetic/MachineArithmetic/pharo/pharo-local/ombu-sessions/Pharo8.0-SNAPSHOT-32bit-6b47e52.2nymi5o1dznxh7tw5uwwkx7zl.ombu@4325378: Illegal leading byte for utf-8 encoding

This commit disables Epicea while loading packages using `pharo-load-local`
macro. This hopefully avoids the above error. As as (welcomed) sideeffect,
Epicea's "Code Changes" browser no longer shows changes representing
loading of a package from source.